---
title: "The Influence Model"
author: "Shimeng Dai"
date: "`r Sys.Date()`"
 
output: 
  html_document:
    code_folding: show
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---

# Load Required Libraries

```{r}
library(dplyr)
library(car)
```

# Datasets

```{r}
# edgelist
data1 <- data.frame(nominator = c(2, 1, 3, 1, 2, 6, 3, 5, 6, 4, 3, 4), 
                    nominee = c(1, 2, 2, 3, 3, 3, 4, 4, 4, 5, 6, 6), 
                    relate = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)) # interaction weight
data1
```

```{r}
# prior attribute measure 
data2 <- data.frame(nominee = c(1, 2, 3, 4, 5, 6), # node ID
                    yvar1 = c(2.4, 2.6, 1.1, -0.5, -3, -1)) 
data2
```

```{r}
# post attribute measure 
data3 <- data.frame(nominator = c(1, 2, 3, 4, 5, 6), # node ID
                    yvar2 = c(2, 2, 1, -0.5, -2, -0.5)) 
data3
```

# Calculate Exposure Term 

```{r}
data <- left_join(data1, data2, by = "nominee")  
data$nominee <- as.character(data$nominee) # this makes merging later easier
```

```{r}
# calculate indegree in tempdata and merge with data
tempdata <- data.frame(table(data$nominee)) # calculate the number of times a node has been nominated as a nominee
names(tempdata) <- c("nominee", "indegree") # rename the column "nominee"
tempdata$nominee <- as.character(tempdata$nominee) # makes nominee a character data type, instead of a factor, which can cause problems
data <- left_join(data, tempdata, by = "nominee") # attach indgree of nominee to the main dataset
head(data, n = 5)
```


```{r}
# Calculating exposure and an exposure term that uses indegree, exposure_plus
data$exposure <- data$relate * data$yvar1
data$exposure
```

```{r}
# Adding 1 to indegree ensures that nodes with zero indegree still get a non-zero exposure_plus value.
# Assign more weight when exposing to someone with a higher indegree
data$exposure_plus <- data$exposure * (data$indegree + 1)
data$exposure_plus
```

```{r}
# Calculating mean exposure
mean_exposure <-
  data %>%
  group_by(nominator) %>%  # calcualte total exposure each nominator receives based on the attributes (yvar1) of the people they nominated.
  summarize(exposure_mean = mean(exposure)) # calculate the average exposure each nominator receives
mean_exposure
```

```{r}
# Calculating mean exposure with indegree
mean_exposure_plus <-
  data %>%
  group_by(nominator) %>%
  summarize(exposure_plus_mean = mean(exposure_plus))
head(mean_exposure_plus, n = 5)
```

```{r}
# need a final data set with mean_exposure, mean_exposure_plus, degree, yvar1, and yvar2 added

mean_exposure_terms <- dplyr::left_join(mean_exposure, mean_exposure_plus, by = "nominator")

names(data2) <- c("nominator", "yvar1") # rename nominee as nominator to merge these
final_data <- dplyr::left_join(mean_exposure_terms, data2, by = "nominator")
final_data <- dplyr::left_join(final_data, data3, by = "nominator") # data3 already has nominator, so no need to change
head(final_data, n = 5)
```

# Model

```{r}
# regression (linear models)
model1 <- lm(yvar2 ~ yvar1 + exposure_mean, data = final_data)
summary(model1)

```
```{r}
avPlots(model1)
```
```{r}
model2 <- lm(yvar2 ~ yvar1 + exposure_plus_mean, data = final_data)
summary(model2)
```
```{r}
avPlots(model2)
```

